# =============================================================================
# Filebeat Configuration for SIEM OpenSource PyMES
# =============================================================================
# This configuration file sets up Filebeat for log collection and forwarding
# in a SIEM environment with multiple input sources and processors
# =============================================================================

# =============================================================================
# FILEBEAT INPUTS
# =============================================================================
filebeat.inputs:

# Configuración específica de Windows incluida directamente
- type: log
  id: windows-demo
  enabled: true
  paths:
    - C:\Windows\Logs\*.log
  fields:
    logtype: windows
    service: system
  fields_under_root: true

# Logs de demostración (siempre habilitados)
- type: log
  id: demo-logs
  enabled: true
  paths:
    - /usr/share/filebeat/logs-ejemplo/*.log
  fields:
    logtype: demo
    environment: development
    source: demo
  fields_under_root: true
  scan_frequency: 5s

# Docker container logs (para el SIEM)
- type: container
  id: docker-logs
  enabled: true
  paths:
    - '/var/lib/docker/containers/*/*.log'
  fields:
    logtype: docker
    service: container
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true

# Configuración simplificada - otros inputs se cargan desde windows-inputs.yml

# =============================================================================
# FILEBEAT MODULES
# =============================================================================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s

# =============================================================================
# PROCESSORS (Configuración simplificada)
# =============================================================================
processors:
# Add basic host information
- add_host_metadata:
    when.not.contains.tags: forwarded

# Add basic tags
- add_tags:
    tags: ["siem", "filebeat"]
    target: "tags"



# =============================================================================
# OUTPUT CONFIGURATION
# =============================================================================
# Elasticsearch output
output.elasticsearch:
  enabled: true
  hosts: ["http://elasticsearch:9200"]
  protocol: "http"
  
  # Index settings
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
  template.name: "filebeat"
  template.pattern: "filebeat-*"
  
# Setup template configuration
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.enabled: true
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  template.settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0
    index.refresh_interval: "30s"
    index.codec: best_compression
  
  # ILM settings
  ilm.enabled: true
  ilm.rollover_alias: "filebeat"
  ilm.pattern: "{now/d}-000001"
  ilm.policy: "filebeat-policy"
  
  # Performance settings
  worker: 2
  bulk_max_size: 1000
  timeout: 90s
  flush_interval: 1s
  compression_level: 3
  
  # Pipeline settings
  pipeline: "filebeat-pipeline"

# Logstash output (alternative)
output.logstash:
  enabled: false
  hosts: ["logstash:5044"]
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]
  ssl.verification_mode: certificate
  worker: 2
  compression_level: 3
  bulk_max_size: 2048
  slow_start: true

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
  rotateeverybytes: 10485760
  interval: 24h

logging.selectors: ["*"]
logging.metrics.enabled: true
logging.metrics.period: 30s

# JSON logging format
logging.json: true
logging.ecs: true

# =============================================================================
# MONITORING CONFIGURATION (Simplificado)
# =============================================================================
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  metrics.period: 10s
  state.period: 1m

# =============================================================================
# HTTP ENDPOINT
# =============================================================================
http.enabled: true
http.host: "0.0.0.0"
http.port: 5066
http.pprof.enabled: false

# =============================================================================
# GENERAL SETTINGS
# =============================================================================
name: "siem-filebeat"
tags: ["siem", "production", "filebeat"]
fields:
  environment: "${ENVIRONMENT:production}"
  datacenter: "${DATACENTER:dc1}"
  project: "siem-pymes"
fields_under_root: true

# Queue settings
queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 1s

# Registry settings
filebeat.registry.path: "/usr/share/filebeat/data/registry"
filebeat.registry.file_permissions: 0600
filebeat.registry.flush: 1s

# Shutdown settings
filebeat.shutdown_timeout: 30s

# =============================================================================
# AUTODISCOVER CONFIGURATION (Deshabilitado)
# =============================================================================
# filebeat.autodiscover:
#   providers: []

# =============================================================================
# SECURITY SETTINGS
# =============================================================================
# SSL/TLS settings
ssl.enabled: true
ssl.verification_mode: certificate
ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]
ssl.certificate: "/usr/share/filebeat/certs/filebeat/filebeat.crt"
ssl.key: "/usr/share/filebeat/certs/filebeat/filebeat.key"

# =============================================================================
# PERFORMANCE TUNING
# =============================================================================
# File harvesting settings
filebeat.inputs:
  close_inactive: 5m
  close_removed: true
  close_renamed: false
  close_eof: false
  clean_inactive: 72h
  clean_removed: true
  ignore_older: 24h
  scan_frequency: 10s
  harvester_buffer_size: 16384
  max_bytes: 10485760
  multiline.timeout: 5s
  tail_files: false
  symlinks: false
  backoff: 1s
  max_backoff: 10s
  backoff_factor: 2

# =============================================================================
# CUSTOM SIEM SETTINGS
# =============================================================================
# Custom settings for SIEM environment
siem:
  threat_intel:
    enabled: true
    feeds:
      - name: "malware_domains"
        url: "https://malware-domains.com/files/domains.txt"
        refresh_interval: "1h"
      - name: "tor_exit_nodes"
        url: "https://check.torproject.org/api/bulk"
        refresh_interval: "6h"
  
  enrichment:
    enabled: true
    geoip: true
    user_agent: true
    dns_resolution: true
  
  alerting:
    enabled: true
    high_priority_events:
      - "authentication_failure"
      - "privilege_escalation"
      - "malware_detected"
      - "data_exfiltration"

# =============================================================================
# DEVELOPMENT SETTINGS
# =============================================================================
# Development settings (disable in production)
filebeat.config.inputs:
  enabled: true
  path: configs/*.yml
  reload.enabled: true
  reload.period: 10s

# =============================================================================
# END OF CONFIGURATION
# =============================================================================