# =============================================================================
# LOGSTASH CONFIGURATION - SIMPLIFIED VERSION
# =============================================================================

# =============================================================================
# NODE CONFIGURATION
# =============================================================================
node.name: "logstash-node-01"
path.data: "/usr/share/logstash/data"
path.logs: "/usr/share/logstash/logs"
path.settings: "/usr/share/logstash/config"

# =============================================================================
# PIPELINE CONFIGURATION
# =============================================================================
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# =============================================================================
# HTTP API CONFIGURATION
# =============================================================================
http.host: "0.0.0.0"
http.port: 9600

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
log.level: info
log.format: plain

# =============================================================================
# MONITORING CONFIGURATION (SIMPLIFIED)
# =============================================================================
monitoring.enabled: false

# =============================================================================
# X-PACK CONFIGURATION (DISABLED)
# =============================================================================
xpack.monitoring.enabled: false
xpack.management.enabled: false

# =============================================================================
# QUEUE CONFIGURATION
# =============================================================================
queue.type: memory
queue.max_events: 0
queue.max_bytes: 1024mb

# =============================================================================
# DEAD LETTER QUEUE
# =============================================================================
dead_letter_queue.enable: false

# =============================================================================
# PERFORMANCE TUNING
# =============================================================================
config.reload.automatic: true
config.reload.interval: 3s
config.support_escapes: false

# =============================================================================
# SECURITY (DISABLED FOR DEVELOPMENT)
# =============================================================================
api.ssl.enabled: false
api.auth.type: none